using BepInEx;
using System.IO;
using UnityEngine;
using GorillaNetworking;

[BepInPlugin("com.yourname.cosmeticdumper", "Cosmetic Dumper", "1.0.0")]
public class CosmeticDumper : BaseUnityPlugin
{
    bool hasDumped = false;

    void Update()
    {
        if (!hasDumped && CosmeticsController.instance != null && CosmeticsController.instance.allCosmetics != null)
        {
            hasDumped = true;
            GrabCosmeticData();
        }
    }

    void GrabCosmeticData()
    {
        string text = "All the current cosmetics from " + System.DateTime.Now.ToString("MM-dd");

        foreach (var item in CosmeticsController.instance.allCosmetics)
        {
            try
            {
                text += "\n====================================\n";
                text += item.itemName + " ; " + item.displayName +
                        " (override " + item.overrideDisplayName + ") ; " +
                        item.cost + "SR ; canTryOn = " + item.canTryOn;
            }
            catch
            {
            }
        }

        text += "\n====================================\n";
        text += "Generated by elliot";

        string outputPath = Path.Combine(Paths.PluginPath, "CosmeticData.txt");
        File.WriteAllText(outputPath, text);
    }
}

